---
title: "Schedule"
description: |
 Schedule and course materials for Statistical Programming Paradigms and Workflows (JHSPH Biostatistics 140.840 Fall 2022).
tbl-colwidths: [15,10, 55, 20]
---

## Schedule and course materials


For Rmd files, go to the [course GitHub repository](https://github.com/stephaniehicks/jhustatprogramming2022) and navigate the directories, or best of all to clone the repo and navigate within RStudio.

::: column-page
| Week         | Dates   | Topics | Projects  |
|---|---|---|---|---|
| **Module 1** | | **Statistical programming at the command-line**  | |
| | | |
| Week 1 | Oct 27  | Course introduction \[[syllabus](syllabus.qmd)\] | `r emojifont::emoji('palm_tree')` Project 1 \[[html](projects/2022-10-27-project-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/projects/2022-10-27-project-1/index.qmd)\]  |
| | | Building websites with `quarto` \[[html](posts/2022-10-27-build-website/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-10-27-build-website/index.qmd)\] | | 
| | | | |
| | | | |
| Week 2 | Nov 1  | Introduction to the command-line \[[html](posts/2022-11-01-command-line-part-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-11-01-command-line-part-1/index.qmd)\]  |   |
| | | | | 
| | Nov 3  | More advanced command-line tools \[[html](posts/2022-11-03-command-line-part-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-11-03-command-line-part-2/index.qmd)\] | |
| | |  | | 
| Week 3  | Nov 8 |  Version control (git) \[[html](posts/2022-11-08-version-control-part-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-11-08-version-control-part-1/index.qmd)\] | `r emojifont::emoji('palm_tree')` Project 2 \[[html](projects/2022-11-08-project-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/projects/2022-11-08-project-2/index.qmd)\]  | 
| | | |                            | | | |
| | Nov 10 | Version control (GitHub) \[[html](posts/2022-11-10-version-control-part-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-11-10-version-control-part-2/index.qmd)\]  |   |
| | | | | 
| | Nov 11 | | `r emojifont::emoji('fallen_leaf')` Project 1 due | 
| | | | | 
| **Module 2** |         | **R software development** | |  
| | | |
| Week 4 | Nov 15 | Object Oriented Programming \[[html](posts/2022-11-15-object-oriented-programming/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-11-15-object-oriented-programming/index.qmd)\] |  | 
| | | | |
| | Nov 17 | R package software development \[[html](posts/2022-11-17-r-pkg-dev-part-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-11-17-r-pkg-dev-part-1/index.qmd)\] | | 
| | | | | 
| Week 5   | Nov 22 | `r emojifont::emoji('turkey')` Class is canceled | | 
| | | | | 
| |  Nov 24 | `r emojifont::emoji('turkey')` No lecture, enjoy the break! | | 
| | | | |
| | Nov 25 | |   |
| | | | |
| **Module 3** |         | **Advanced programming paradigms** | |  
| | | | | 
| Week 6 | Nov 29 | Functional programming with `purrr` \[[html](posts/2022-11-29-purrr-fun-programming/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-11-29-purrr-fun-programming/index.qmd)\] | `r emojifont::emoji('fallen_leaf')` Project 2 due  <br /> `r emojifont::emoji('palm_tree')` Project 3  \[[html](projects/2022-11-22-project-3/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/projects/2022-11-22-project-3/index.qmd)\]  |
| | | | | 
| | Dec 1  | Project management with `targets` \[[html](posts/2022-12-01-targets-proj-workflows/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-12-01-targets-proj-workflows/index.qmd)\] | |
| | | Package website with `pkgdown` \[[html](posts/2022-12-01-pkgdown-pkg-website/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-12-01-pkgdown-pkg-website/index.qmd)\]  | |
| | | | | 
| Week 7 | Dec 6  | Retrieving data from APIs \[[html](posts/2022-12-06-gettingdata-api/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-12-06-gettingdata-api/index.qmd)\] | | 
| |  |  | |
| | | |
| | Dec 8 | Relational databases and SQL basics \[[html](posts/2022-12-08-relational-databases/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-12-08-relational-databases/index.qmd)\]  | | 
| | | |
| **Module 4** |  | **Interactive web apps and dashboards**  | | 
| | | |
|  Week 8 | Dec 13  |  Building dashboards with `flexdashboard` and `shinydashboard` \[[html](posts/2022-12-13-flexdashboard/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-12-13-flexdashboard/index.qmd)\]   | `r emojifont::emoji('fallen_leaf')` Project 3 due  <br />  `r emojifont::emoji('palm_tree')` Project 4 \[[html](projects/2022-12-06-project-4/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/projects/2022-12-06-project-4/index.qmd)\] | 
| | | |
| | Dec 15  | Scraping data from the web with `rvest` \[[html](posts/2022-12-15-web-rvest/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-12-15-web-rvest/index.qmd)\]  |  | 
| | | |
| **Module 5** |  | **Dealing with "big" data**  | | 
| | | |
| Week 9       | Dec 20  | Profiling R code  \[[html](posts/2022-12-20-profiling-r-code/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatprogramming2022/blob/main/posts/2022-12-20-profiling-r-code/index.qmd)\] |  | 
| | | Strategies for dealing with large data | | 
| | | |
| | Dec 22 | `r emojifont::emoji('snowflake')` Class is canceled | | 
| | | |
| | Dec 23  | | `r emojifont::emoji('fallen_leaf')` Project 4 due  |
:::


