---
title: "Syllabus"
---

## Course Information

-   Location: In person (with recorded lectures posted online) for Fall 2022
-   Course time: Tuesdays and Thursdays from 1:30-2:50pm (**Eastern Daylight Time** zone)
-   Course location: TBA
-   Assignments: Four projects

### How to register and participate

- **To add the course to your 2nd term registration**: Sign up for 3 credits of 140.840, with Dr. Hicks as the instructor. 
- Please note that 800-level courses are pass/fail only
- Please note BSPH does not allow auditors in 800-level courses
- Please note there is no formal `.41` online course for 800-level courses. However, this course will have the lectures recorded and posted on CoursePlus. You can watch all lecture material and complete the assignments asynchronously, if you wish. 

### Instructor

-   Stephanie C. Hicks (<https://www.stephaniehicks.com>)
    -   Office Location: E3545, Wolfe Street building
    -   Email: shicks19\@jhu.edu

Instructor office hours are announced on CoursePlus. If there are conflicts and/or need to cancel office hours, announcements will be made on CoursePlus.

### Getting help

In order of preference, here is a preferred list of ways to get help:

1.  We **strongly encourage** you to use CoursePlus to ask questions first, before joining office hours. The reason for this is so that other students in the class (who likely have similar questions) can also benefit from the questions and answers asked by your colleagues.
2.  You are welcome to join office hours to get more group interactive feedback.
3.  If you are not able to make the office hours, appointments can be made by email with the instructor.

## Important Links

-   Course website: <https://stephaniehicks.com/jhustatprogramming2022>
-   GitHub repository with all course material: <https://github.com/stephaniehicks/jhustatprogramming2022>

## Learning Objectives:

Upon successfully completing this course, students will be able to:

1.  Write unix code with command-line tools
2.  Install and configure software necessary for a statistical programming environment and with version control
3.  Write code for advanced programming topics in R and tidyverse
4.  Build and organize a software package with documentation for publishing on the internet
5.  Write code using functional or other programming paradigms and discuss strategies for getting data from APIs or working with large data
6.  Build an interactive web application using Shiny or other dashboard tools

## Lectures

In Fall 2022, we will have in person lectures that will be recorded and posted online for students to watch. **Mandatory attendance is not required.**

## Textbook and Other Course Material

There is no required textbook. We will make use of several freely available textbooks and other materials. All course materials will be provided. We will use the R software for data analysis, which is freely available for download.

## Software

We will make heavy use of R in this course, so you should have R installed. You can obtain R from the [Comprehensive R Archive Network](https://cran.r-project.org). There are versions available for Mac, Windows, and Unix/Linux. This software is **required** for this course.

It is important that you have the latest version of R installed. For this course we will be using **R version `r paste(version$major, version$minor, sep = ".")`**. You can determine what version of R you have by starting up R and typing into the console `R.version.string` and hitting the `return`/`enter` key. If you do not have the proper version of R installed, go to [CRAN](https://cran.r-project.org) and download and install the latest version.

We will also make use of the RStudio interactive development environment (IDE). RStudio requires that R be installed, and so is an "add-on" to R. You can obtain the RStudio Desktop for free from the [RStudio web site](https://www.rstudio.com/). In particular, we will make heavy use of it when developing R packages. It is also essential that you have the latest release of RStudio. You can determine the version of RStudio by looking at menu item `Help > About RStudio`. You should be using **RStudio version 1.4.1106 or higher**.

## Projects

There will be 4 assignments, due every 2--3 weeks. Projects will be submitted electronically via the Drop Box on the CoursePlus web site (unless otherwise specified).

The project assignments will be due on

-   Project 1: Friday November 11, 11:59pm
-   Project 2: Friday November 25, 11:59pm
-   Project 3: Friday December 9, 11:59pm
-   Project 4: Friday December 23, 11:59pm

### Project collaboration

Please feel free to study together and talk to one another about project assignments. The mutual instruction that students give each other is among the most valuable that can be achieved.

However, it is expected that **project assignments will be implemented and written up independently unless otherwise specified**. Specifically, please do not share analytic code or output. Please do not collaborate on write-up and interpretation. Please do not access or use solutions from any source before your project assignment is submitted for grading.

## Discussion Forum

The course will make use of the CoursePlus Discussion Forum in order to ask and answer questions regarding any of the course materials. The Instructor and the Teaching Assistants will monitor the discussion boards and answer questions when appropriate.

## Exams

There are **no exams** in this course.

## Grading

Grades in the course will be based on Projects 1--4 with a percentage of the final grade being apportioned to each assignment. Each of Projects 1--4 counts approximately equally in the final grade. Grades for the projects and the final grade will be issued via the CoursePlus grade book.

## Academic Ethics and Student Conduct Code

Students enrolled in the Bloomberg School of Public Health of The Johns Hopkins University assume an obligation to conduct themselves in a manner appropriate to the University's mission as an institution of higher education. A student is obligated to refrain from acts which he or she knows, or under the circumstances has reason to know, impair the academic integrity of the University. Violations of academic integrity include, but are not limited to: cheating; plagiarism; knowingly furnishing false information to any agent of the University for inclusion in the academic record; violation of the rights and welfare of animal or human subjects in research; and misconduct as a member of either School or University committees or recognized groups or organizations.

Students should be familiar with the policies and procedures specified under Policy and Procedure Manual Student-01 (Academic Ethics), available on the school's [portal](http://my.jhsph.edu).

The faculty, staff and students of the Bloomberg School of Public Health and the Johns Hopkins University have the shared responsibility to conduct themselves in a manner that upholds the law and respects the rights of others. Students enrolled in the School are subject to the Student Conduct Code (detailed in Policy and Procedure Manual Student-06) and assume an obligation to conduct themselves in a manner which upholds the law and respects the rights of others. They are responsible for maintaining the academic integrity of the institution and for preserving an environment conducive to the safe pursuit of the School's educational, research, and professional practice missions.

## Disability Support Service

Students requiring accommodations for disabilities should register with [Student Disability Service (SDS)](https://publichealth.jhu.edu/about/inclusion-diversity-anti-racism-and-equity-idare/student-disability-services). It is the responsibility of the student to register for accommodations with SDS.  Accommodations take effect upon approval and apply to the remainder of the time for which a student is registered and enrolled at the Bloomberg School of Public Health.
Once you are f a student in your class has approved accommodations you will receive formal notification and the student will be encouraged to reach out. If you have questions about requesting accommodations, please contact `BSPH.dss@jhu.edu`.



## Prerequisites

Prerequisite for the course is [Biostatistics 140.776](https://www.jhsph.edu/courses/list/?keyword=140.776) or knowledge of material from 140.776 is assumed. 

If you did not take the above course, please contact course instructor to get permission to enroll.

## General Disclaimers

-   This syllabus is a general plan, deviations announced to the class by the instructor may be necessary.
