---
title: "Building a brand and websites with `quarto`"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "Building a brand and websites with `quarto`"
date: 2022-10-27
categories: [module 1, week 1, websites, quarto]
---

<!-- Add interesting quote -->

# Pre-lecture materials

### Read ahead

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1.  Add here.
2.  Add here.
:::

### Acknowledgements

Material for this lecture was borrowed and adopted from

- 
- 

# Learning objectives

::: callout-note
# Learning objectives

**At the end of this lesson you will:**

-   Add here.
:::

# Building a brand as a scientist

Making discoveries and contributing your ideas and/or work are fundamental components of being a scientist (I am treating of the word "scientist" very broadly here). However, another important component of being a scientist is learning how to build your "brand" as a scientist. 
I want to preface this blog post acknowledging there are huge differences across cultures and the content in this post might even be in contrast to what is the norm in a different culture. I write this blog post from my own perspective as a scientist working in the US today.

Now, lots of people have written about this topic, but I do not think this topic is discussed enough with early career researchers and scientists, in particular at the stage of a graduate student or postdoctoral scientist. However, it can have a potentially large impact on someone's career. Therefore, I thought I would write down some of the things I have thought about as important for helping me think about building my own brand in academia. Many of these ideas translate to building a brand in industry too. I hope this will help others think about these ideas for their own careers as scientists. 

## Your "brand" is happening with or without your input

The first thing that should be mentioned is your "brand" is built with or without your input (whether you recognize it or not). You may have thought about this topic in the past (formally or informally) or you may not have. Either way, as you develop your career as a scientist you make choices (e.g. what areas to work in, what conferences to attend, how open is your science, whether to have a blog or not, etc) that other people perceive and interpret as your "brand". It is worth taking a bit of time to think about what your brand is (or what you want your brand to be). It can not only help you in terms of becoming more well-known in your field, but it can also help influence your actual science (e.g. what you choose or not choose to work on). 

## Defining your brand

In terms of defining your brand, there are several questions that you might think about: 

- Who are you? What makes you special? 
- What do you stand for? For example, maybe you are passionate about open science and you prioritize publishing in open-access journals or publishing open source software. 
- Who is your audience? This is important in terms of helping you understand your professional community as a scientist. What does the community value or not value? Does this align with your interests? 
- What is your goal? This is a very personal question and there are no wrong answers. However, it is helpful to understand what your short-term and long-terms goals are. Some questions you might think about as you try to answer these two questions are: 
  - What motivates you?
  - What projects have others complimented you on? 
  - Which projects can I spend hours on and not feel overwhelmed or drained?
  - Fill in the following: "I want to be a leader in … <<insert niche field>>"
  - "In 5-10 years, I want to ... << insert thing you want to have accomplished >>"

Answering these (and other questions) can help you put your best foot forward for whatever type of job you take in the future (industry, academia, nonprofit, etc). These are also very helpful in defining what you want your brand to be. 


## Actions to take towards building a brand as a scientist

#### Think of yourself as a self-startup

This is definitely true as a faculty member, but many aspects of this are true as a graduate student or postdoctoral scientist. However, when you are early in your career, it is true that you may have less say in _what_ you work on, but as you grow into your career, you will likely have more and more say. Therefore, this section becomes more and more relevant. 

For example, as you advance in your career there will likely be increasing opportunities for you to decide what to work on, how much time and effort to spend on the projects, how to convince others these are exciting projects, how to fund the projects, how to market the products you produce, how to lead teams of individuals to make progress on these projects. It is important to realize (earlier the better) that a lot of this is like starting up your own company. It takes many, many different skills (both scientific skills and professional development / soft skills) to be successful at it. You want to invest time and energy in developing these skills (sooner rather than later) as they are likely to have huge benefits down the road. 

For example, let's say you are grabbing a cup of coffee at a conference. You bump into someone in the coffee line from the last session that you were in. You have some small talk about the previous session and the person asks you about what do you or what do you work on? This might be very informal, but it is a great opportunity for you to have developed (and hopefully practiced) an [elevator pitch](https://en.wikipedia.org/wiki/Elevator_pitch). These are crucial in the world of startups. They require good communication skills and for you to have a solid understand of who you are, what you are passionate about, and why someone else should care about it. This one, informal conversation may not lead to anything, but in my experience, I have been surprised at how many times it does lead to something down the line (e.g. an email with a link to a paper relevant to your work that you were not aware of, a connection with someone at another institute who might think of you next time they are looking for speakers, a new collaboration, etc). These connections are similar in the world of startups and can sometimes be transformative to your career as a scientist. 


#### Want to develop a consistent brand

As you start to develop your brand, you want to think about consistency. Similar to the point above, this applies less to graduate students as they are likely to want to try different things out. However, this becomes more relevant as you grow into your career as a scientist. If your brand is inconsistent, it can be hard for others to understand what you are about, what your interests are, etc. If you did a pretty good job at defining your brand, this action item is a bit easier. 

For example, if your audience is academic, theoretical computer scientists, you want to think about publishing in journals and attending conferences to present your work where other academic computer scientists are. It may not make much sense to attend psychology or biology conferences. However, maybe your audience is a diverse set of scientists bridging two fields (e.g. psychology and computer science) -- therefore, you might be attending a broader set of conferences from both types of fields. Either way, you want to develop the skills (both scientific and professional development skills) needed to enable you to be successful in your field(s) of interest. Spending time on completely orthogonal skills that are not essential to building your brand, might be fun, but it is not necessarily going to help you move towards your goal. You want to develop a brand in the places where you will have a big impact and become well-known for your work.

Now all this can potentially take years. It is unlikely you will do this over night. However, it is important to be thinking about consistency as you build your brand. 

#### Learn how to effectively self-promote your work 

I think we can all agree that contributing to science itself is essential for being a scientist. However, I often find people might not be good at the follow up step -- namely, effectively communicating about their work to a broad audience in a succinct way, and promoting their own work (or work of collaborators). Putting a paper on bioRxiv or getting it through peer-review is, **of course, a major accomplishment**. However, the world we live in moves far too fast for me to be able to keep up with everyone's work that I want to keep up with. It is incredibly helpful when a scientist takes that extra step to invest time and energy in promoting their work beyond just publishing a manuscript. If they were effective at this, I might not understand all the details, but I have a good sense of what their contribution is and why I might care about. 

There are many great ways to go about doing this. Not all of them may be relevant for you. Social media is one way that is commonly discussed as a mechanism to promote your work. However, you may be in a situation where having a social media presence could potentially put you in harms way, so you prefer to not engage on social media platforms, but rather promote your work in other ways. I want to emphasize there is no one "correct" way of doing this! Find the tools that work for you. 

All this being said, if you feel comfortable with having an online presence, it can be a helpful way to effectively self-promote your work. For example, creating a simple website (that is easy to maintain and update) can be helpful in keeping track of your accomplishments and sharing them with others. Investing time and energy in making a good CV (or resume depending on your field of interest) is another good way. Being able to quickly quantify your accomplishments if and when someone asks is another. Creating a blog and actively contribute to the blog is another. 

#### Leveraging social media to your benefit ("promote" your brand)

If you do decide to go down the social media route, you want to be selective with your platforms. **Do not try to be on every platform**. It can be a huge time sink to invest in the energy of being on just one or two platforms. 

Let's say you choose to be active on Twitter. There are different strategies for engaging on the platform. For example, some folks engage a lot in a bidirectional fashion (i.e. they post a lot of tweets, but they also engage in many conversations with other people's tweets). In contrast, others may choose to engage in a more unidirectional fashion (i.e. they use the platform to tweet about their own work and do not really engage in other people's tweets). Other folks join the platform to just follow along with other people's tweets and do not really engage in conversations at all. All of these have very different degrees of time required to engage with the platform. With that in mind, these are trade-offs that you make as a scientist. Time that you spent on e.g. Twitter is time that you could have spent working on science itself. However, not communicating about your science is also not great. You want to find a balance that works for you. 

If you have a recent pre-print or paper out, one strategy to promote your work is to write a [tweetorial](https://www.urbandictionary.com/define.php?term=Tweetorial). I have found this as an effective tool to distill scientific ideas (e.g. from a pre-print) down to something that is bite-sized and understandable in a few minutes. If someone reading the tweetorial thinks it is interesting, they might choose to click on the link to the pre-print and read a bit more. In contrast, if I had not taken the extra effort to distill these ideas down, this individual might have missed the pre-print all together. Having someone read about my work can influence their perception of my "brand". For example, this individual might think of me next time they come across a similar topic or they might invite me to give a seminar on the topic. 

I will state that Jeff Leek wrote a great book titled _How to be a Modern Scientist_ available on [leanpub](https://leanpub.com/modernscientist) with a lot of these ideas. Highly recommended to check it out! 

#### Embrace networking

Let's face it, networking can be transformative when it comes to being a scientist. It can open so many doors at a variety of levels. It can lead to future talk invitations, potential recommendation letters, future collaborations, potential internships. The list goes on and on. 

It is also important to note the benefits you get out of networking and _how you network_ can change as you grow into your career. For example, when you are just starting out as a graduate student, you may not know many folks at conferences. Here, it is all about putting yourself out there, introducing yourself to someone else, starting up a conversation over a coffee break, attending poster sessions, asking questions to speakers at the end of sessions, etc. As you grow in your career as a scientist, you start to develop professional friendships with colleagues and you may choose to connect with them at an annual conference in your professional field. 

For example, one strategy I have found effective for me in my current stage is ahead of the conference, I schedule breakfasts / coffee breaks / lunches / dinners with people that I want to see there. It ensures that I am able to connect and network with the folks that I am most interested in connecting with. I may or may not have met these individuals before. It all depends on what the purpose is of the meeting. For example, if I am a graduate student wanting to learn more about opportunities for doing a posdoc in a different a department, I might reach out to someone from that department who is attending the conference and ask to meet for 15 mins to ask questions. Alternatively, I may catching up with an old friend. Either way, I cannot emphasize enough how much networking has helped my career and helped shape my "brand". 

#### Re-invent your brand as you grow / change over time

The last thing I want to mention is that your brand may change over time. As you as a scientist evolves, your brand may need to evolve. Recognizing when that is happening and embracing it is not only healthy, but completely normal. 

# Post-lecture materials

### Final Questions

Here are some post-lecture questions to help you think about the material discussed.

::: callout-note
### Questions

1.  Add here.
:::

### Additional Resources

::: callout-tip
-   Add here.
:::
