---
title: "Project 1"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "TBA"
date: 2022-10-27
draft: true
categories: [project 1, projects]
---

# Background


**Due date: November 11 at 11:59pm**

The goal of this assignment is to... 

### To submit your project

# Part 1

Complete the Git & GitHub Fundamentals Starter course. The link to create a private GitHub repository for yourself to complete the course will be posted in CoursePlus. When you are done, add the link to the GitHub repo here: 

- **Action**: Delete this text and replace the text with the link to the private GitHub repo you created above


# Part 2

This part of the project is to help you introduce yourself (and your interests!) to others in this course. You will create a new GitHub repository and build a small website about yourself.

## 1. Create a GitHub repo for your website

Create a new GitHub repository titled `biostat840-intro-<firstname>-<lastname>` (where you replace `<firstname>` with your first name and `<lastname>` with your last name) in your own personal GitHub account (e.g. `https://github.com/<yourgithubusername>/biostat840-intro-<firstname>-<lastname>`).

### 2. Build a website using `quarto`

Create a new project locally within RStudio and build a website for yourself. Your website should include the following: 

- A landing page. This is home page that someone will land on your website. At minium it should include a picture of yourself, your name, and a short summary about yourself (max 2-3 sentences). 
- An `About` page. This page should describe who you are in greater detail. It could include your professional interests and your educational and/or professional background and/or experience. It could also include any personal information you feel conformtable sharing on the website.
- A data analysis page called `Example data analysis`. You can pick any dataset you wish you analyze. In this webpage, you will analyze a dataset and summarize it. The requirements for this webpage are the following: 
    - You must describe what is the question you aim to answer with the data and data analysis. 
    - You must describe who is the intended audience for the data analysis. 
    - You must describe and link to where the original data come from tha you chose. You must also include a link to a data dictionary or create one inside the webpage. 
    - Your analysis must include some minimal form of data wrangling with you using at least five differnt functions from `dplyr` or `tidyr`. 
    - Your analysis should include at least three plots with you using at least three different `geom_*()` functions from `ggplot2` (or another package with `geom_*()` functions). Plots should have titles, subtitles, and axis labels. 
    - At least plot should using a type of faceting (`facet_grid()` or `facet_wrap()`). 
    - Your analysis must include one figure or table (not one you created yourself, but one you have saved locally or one from the web). 
    - Your analysis must include at least two different [callout blocks](https://quarto.org/docs/authoring/callouts.html).
    - Your analysis must include a `.bib` file, which you use to reference at least three unique citations. For example, it could be to a website or paper from where the original data came from or it could be to a paper describing a method you are using to analyze the data. 
    - Your analysis must include the use of at least 1 footnote. 
    - You must summarize your analysis and/or results with a paragraph (4-6 sentences).
    - At the end of the data analysis, list out each of the functions you used from each of the package to help the TA with respect to making sure you met all the requirements described above. 

### 3. Include a `README.md` file

Your GitHub repository should include a `README.md` file describing who is the author of the website and a link to the website that has been deployed. You can also describe the technical details for how the website was created and/or deployed. 

### 4. Deploy your website

Deploy your website using [Quarto Pub](https://quarto.org/docs/publishing/quarto-pub.html), [GitHub pages](https://quarto.org/docs/publishing/github-pages.html), or [Netlify](https://quarto.org/docs/publishing/netlify.html). (**Note**: Deploying your website to RPubs will not be accepted).

### 5. Share your website

Go to the Discussion Board in CoursePlus and write a short post with a link (URL) to your website (and URL to the corresponding GitHub repository) that you created. Also, list the URLs below for the purposes of grading. 

As you read the introductions from other folks in the class, feel free to comment/reply using Discussion board.

- **Action**: Delete this text and replace the text with the link to the GitHub repo you created above
- **Action**: Delete this and replace the text with the link to the the deployed website you created above


# Part 3





